#pragma once

#include <pebble.h>

#define FG_COLOR GColorWhite
#define BG_COLOR GColorBlack

#define CIRCLE_FG_COLOR GColorBlack
#define CIRCLE_BG_COLOR GColorDarkGray

#define TIME_LAYER_BK_COLOR GColorBlue
#define DATE_LAYER_BK_COLOR GColorGreen
#define WEATHER_LAYER_BK_COLOR GColorRed
#define TEMPERATURE_LAYER_BK_COLOR GColorCadetBlue
#define COUNTDAYS_LAYER_BK_COLOR GColorPurple

#define CIRCLE_THICKNESS 10
#define CIRCLE_ANG_START -180
#define CIRCLE_ANG_END 180

#define WINDOW_STACK_PUSH_ANIMATED true

#define TIME_LAYER_TOP 142
#define TIME_LAYER_HEIGHT 50

#define APP_MESSAGE_INBOX_SIZE 128
#define APP_MESSAGE_OUTBOX_SIZE 128

#define WEATHER_GET_EVERY_MINUTES 30

#define COUNTDAYS_START_DATE_KEY 5
#define COUNTDAYS_START_DATE_DEFAULT "2016-02-29T16:00:00.000Z"
