#pragma once

#include <pebble.h>

#define FG_COLOR GColorWhite
#define BG_COLOR GColorDarkGray

#define CIRCLE_FG_COLOR GColorBlack
#define CIRCLE_BG_COLOR GColorDarkGray

#define TIME_LAYER_BK_COLOR GColorBlack
#define TIME_LAYER_FG_COLOR GColorWhite

#define DATE_LAYER_BK_COLOR GColorCadetBlue
#define DATE_LAYER_FG_COLOR GColorWhite

#define WEATHER_LAYER_BK_COLOR GColorDarkGray
#define WEATHER_LAYER_FG_COLOR GColorBlack

#define TEMPERATURE_LAYER_BK_COLOR GColorDarkGray
#define TEMPERATURE_LAYER_FG_COLOR GColorBlack

#define COUNTDAYS_LAYER_BK_COLOR GColorCadetBlue
#define COUNTDAYS_LAYER_FG_COLOR GColorBlack


#define CIRCLE_THICKNESS 10
#define CIRCLE_ANG_START -180
#define CIRCLE_ANG_END 180

#define WINDOW_STACK_PUSH_ANIMATED true

#define TIME_LAYER_TOP 63
#define TIME_LAYER_HEIGHT 55

#define COUNTDAYS_LAYER_LEFT 40
#define COUNTDAYS_LAYER_TOP 25
#define COUNTDAYS_LAYER_WIDTH 60
#define COUNTDAYS_LAYER_HEIGHT 38

#define DATE_LAYER_LEFT 90
#define DATE_LAYER_TOP 25
#define DATE_WIDTH 90
#define DATE_HEIGHT 38
#define DATE_LAYER_LEFT_SHIFT 18

#define WEATHER_LAYER_TOP 113
#define WEATHER_LAYER_HEIGHT 23

#define TEMPERATURE_LAYER_TOP 136
#define TEMPERATURE_LAYER_HEIGHT 33

#define APP_MESSAGE_INBOX_SIZE 256
#define APP_MESSAGE_OUTBOX_SIZE 256

#define WEATHER_GET_EVERY_MINUTES 20

#define DREAMDAY_KEY 5
#define DREAMDAY_DEFAULT "2014-11-13T16:00:00.000Z"
